package com.ehealth.dermassist.network

import com.ehealth.dermassist.network.model.SkinAnalysisRequest
import com.ehealth.dermassist.network.model.SkinAnalysisResponse
import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.Header
import retrofit2.http.POST
import retrofit2.http.Path

/**
 * Retrofit service interface for the Skin Analysis API.
 * The implementation of this interface is generated by Retrofit at runtime.
 */
interface SkinAnalysisService {

    @POST("task/skin-analysis")
    suspend fun startAnalysis(
        @Header("Authorization") auth: String,
        @Body request: SkinAnalysisRequest
    ): Response<SkinAnalysisResponse>

    @GET("task/skin-analysis/{taskId}")
    suspend fun getAnalysisResult(
        @Header("Authorization") auth: String,
        @Path("taskId") taskId: String
    ): Response<SkinAnalysisResponse>
}
